apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microk8s-tutorial
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/rasputin2/microk8s-tutorial.git
    targetRevision: main
    path: microk8s

  destination:
    server: https://kubernetes.default.svc
    namespace: microk8s-tutorial

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true