apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: microk8s-tutorial
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/rasputin2/backend:4cba8178c7ead7161761654abbe68ec3e100ae50
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: microk8s-tutorial
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
