apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: microk8s-tutorial
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/rasputin2/frontend:411168e7078110d2f817d74ea5e8711d82875dbc
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          env:
            - name: BACKEND_URL
              value: "http://backend-service:8000"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: microk8s-tutorial
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 8501
